@extends('layouts.app')

@section('content')
<x-breadcrumb :items="[['label' => 'Sokoni', 'url' => route('web.home')], ['label' => __('site.footer_privacy_link'), 'url' => null]]" />

<article class="mx-auto max-w-3xl px-16 pb-64 lg:px-24">
@if (app()->getLocale() === 'sw')
    <h1 class="text-2xl font-bold">Sera ya Faragha — toleo {{ \App\Support\Legal::TERMS_VERSION }}</h1>
    <p class="mt-4 text-sm text-sokoni-black/50">Ilisasishwa mwisho: 2026</p>
    <div class="prose prose-sm mt-24 max-w-none space-y-16 text-sokoni-black/80">
        <section><h2 class="font-semibold text-sokoni-black">1. Tunachokusanya</h2><p>Akaunti: jina, nambari ya simu au barua pepe, na picha ya wasifu, kutoka kwako moja kwa moja au kutoka Google/Apple ukijisajili kwa njia hiyo.</p><p>Uthibitisho wa muuzaji: namba ya NIDA — hutumika tu na timu yetu ya uthibitisho, haionyeshwi hadharani.</p><p>Mahali: mahali pa kifaa chako, kwa ridhaa yako, hutumika kuonyesha wauzaji na bidhaa za karibu. Unaweza kukataa na kuchagua mkoa/wilaya kwa mkono badala yake.</p><p>Matumizi: bidhaa unazotazama au kupenda, oda unazoweka, ujumbe unaotuma, na maoni unayotoa.</p><p>Kifaa: alama ya arifa za push, ili tuweze kukujulisha kuhusu oda na ujumbe.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">2. Jinsi tunavyotumia</h2><p>Kuendesha soko — kukuonyesha bidhaa/wauzaji husika, kuchakata oda, kuwezesha mazungumzo, na kuthibitisha wauzaji. Kudumisha usalama wa jukwaa — kuchunguza ripoti, kutekeleza Masharti yetu, na kuzuia udanganyifu. Kuwasiliana nawe — masasisho ya oda, taarifa za akaunti, na (ukikubali) masasisho ya bidhaa.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">3. Tunashiriki na nani</h2><p>Watumiaji wengine wanaona kile unachotarajia kutoka soko: jina lako na picha kwenye maoni na ujumbe wako, maelezo ya duka lako ikiwa wewe ni muuzaji. Hatuuzi taarifa zako binafsi. Tunashiriki taarifa na watoa huduma wanaotusaidia kuendesha Sokoni (mfano, uhifadhi, arifa za push), chini ya wajibu wa usiri, na na mamlaka pale inapohitajika kisheria.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">4. Namba yako ya NIDA</h2><p>Namba ya NIDA hukusanywa tu kuthibitisha kuwa muuzaji ni mtu au biashara halisi, kama ulinzi dhidi ya maduka ya udanganyifu. Taarifa hii inaonekana tu kwa timu yetu ya uthibitisho na haionyeshwi kamwe kupitia API ya hadharani ya programu au kwa watumiaji wengine.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">5. Chaguo zako</h2><p>Unaweza kukataa ruhusa ya mahali wakati wowote — Sokoni itarudi kwenye uchaguzi wa eneo kwa mkono. Unaweza kuomba nakala ya taarifa zako au kutuomba tufute akaunti yako kwa kuwasiliana na {{ config('sokoni.support_email') }}. Kufuta akaunti yako huondoa taarifa zako binafsi, ingawa baadhi ya rekodi (kama oda zilizokamilika) zinaweza kuhifadhiwa pale sheria inapohitaji.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">6. Uhifadhi wa data</h2><p>Tunahifadhi taarifa zako kwa muda akaunti yako inapokuwa hai, pamoja na muda wa kutosha baadaye kwa madhumuni ya kisheria, uhasibu, na kuzuia udanganyifu.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">7. Watoto</h2><p>Sokoni haikusudiwi kwa watoto chini ya miaka 18. Hatukusanyi taarifa za watoto kwa makusudi.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">8. Mabadiliko ya sera hii</h2><p>Tunaweza kusasisha Sera hii ya Faragha mara kwa mara. Mabadiliko makubwa yatahitaji ukubali toleo jipya kabla ya kuendelea kutumia Sokoni.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">9. Mawasiliano</h2><p>Maswali kuhusu Sera hii ya Faragha, au maombi kuhusu taarifa zako, yanaweza kutumwa kwa {{ config('sokoni.support_email') }}.</p></section>
    </div>
@else
    <h1 class="text-2xl font-bold">Privacy Policy — version {{ \App\Support\Legal::TERMS_VERSION }}</h1>
    <p class="mt-4 text-sm text-sokoni-black/50">Last updated: 2026</p>
    <div class="prose prose-sm mt-24 max-w-none space-y-16 text-sokoni-black/80">
        <section><h2 class="font-semibold text-sokoni-black">1. What we collect</h2><p>Account: name, phone number or email, and profile photo, from you directly or from Google/Apple when you sign in that way.</p><p>Seller verification: your NIDA number — used only by our verification team, never shown publicly.</p><p>Location: your device's approximate or precise location, if you grant permission, used to show nearby sellers and products. You can decline and pick a region/district manually instead.</p><p>Usage: products you view or favourite, orders you place, messages you send, and reviews you leave.</p><p>Device: a push-notification token, so we can notify you about orders and messages.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">2. How we use it</h2><p>To operate the marketplace — showing you relevant products/sellers, processing orders, enabling chat, and verifying sellers. To keep the platform safe — investigating reports, enforcing our Terms, and preventing fraud. To communicate with you — order updates, account notices, and (if you opt in) product updates.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">3. Who we share it with</h2><p>Other users see what you'd expect from a marketplace: your name and photo on your reviews and messages, your shop details if you're a seller. We do not sell your personal data. We share data with service providers who help us operate Sokoni (e.g. hosting, push notifications), under confidentiality obligations, and with authorities when legally required.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">4. Your NIDA number</h2><p>NIDA numbers are collected solely to verify that a seller is a real, identifiable person or business, as a defence against fraudulent shops. This data is visible only to our verification team and is never exposed through the app's public API or shown to other users.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">5. Your choices</h2><p>You can decline location access at any time — Sokoni falls back to manual area selection. You can request a copy of your data or ask us to delete your account by contacting {{ config('sokoni.support_email') }}. Deleting your account removes your personal data, though some records (like completed orders) may be retained where required by law.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">6. Data retention</h2><p>We retain your data for as long as your account is active, plus a reasonable period afterward for legal, accounting, and fraud-prevention purposes.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">7. Children</h2><p>Sokoni is not directed at children under 18. We do not knowingly collect data from children.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">8. Changes to this policy</h2><p>We may update this Privacy Policy from time to time. Material changes will require you to accept the new version before continuing to use Sokoni.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">9. Contact</h2><p>Questions about this Privacy Policy, or requests regarding your data, can be sent to {{ config('sokoni.support_email') }}.</p></section>
    </div>
@endif
</article>
@endsection
