@extends('layouts.app')

@section('content')
<x-breadcrumb :items="[['label' => 'Sokoni', 'url' => route('web.home')], ['label' => 'Terms of Service', 'url' => null]]" />

<article class="mx-auto max-w-3xl px-16 pb-64 lg:px-24">
@if (app()->getLocale() === 'sw')
    <h1 class="text-2xl font-bold">Masharti ya Huduma — toleo {{ \App\Support\Legal::TERMS_VERSION }}</h1>
    <p class="mt-4 text-sm text-sokoni-black/50">Yalisasishwa mwisho: 2026</p>
    <div class="prose prose-sm mt-24 max-w-none space-y-16 text-sokoni-black/80">
        <section><h2 class="font-semibold text-sokoni-black">1. Sisi ni akina nani</h2><p>Sokoni ("sisi") inaendesha programu na tovuti ya soko la Sokoni, inayounganisha wanunuzi na wauzaji nchini Tanzania. Masharti haya yanasimamia matumizi yako ya Sokoni.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">2. Akaunti yako</h2><p>Unaweza kutazama Sokoni bila akaunti. Kufungua akaunti (kwa nambari ya simu, Google, au Apple) inahitajika ili kuagiza, kuzungumza na muuzaji, au kuhifadhi vipendwa. Wewe ndiye unayehusika na usalama wa taarifa za akaunti yako na shughuli zote chini yake.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">3. Kununua kwenye Sokoni</h2><p>Sokoni ni soko linalounganisha wanunuzi na wauzaji — sisi si sehemu ya mauzo yenyewe. Oda, bei, uwasilishaji na masharti ya malipo hukubaliwa kati yako na muuzaji. Malipo kwa sasa ni malipo baada ya kuletewa au wakati wa kuchukua pekee.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">4. Kuuza kwenye Sokoni</h2><p>Ili kuuza, lazima ukamilishe usajili wa muuzaji, ukiwemo kutoa namba halali ya NIDA na picha ya kitambulisho chako, pamoja na leseni ya biashara. Taarifa hii hutumika tu kwa uthibitishaji wa kibinafsi na timu yetu na haionyeshwi hadharani. Kuwasilisha taarifa za uongo za utambulisho au leseni kutasababisha kusimamishwa au kufutwa kwa akaunti.</p><p>Duka na bidhaa zako zinaweza kuonekana kwa wanunuzi mara akaunti yako itakapothibitishwa. Kabla ya uthibitisho, bidhaa zako hazitaonekana kwenye utafutaji wa hadharani, ingawa unaweza kuendelea kujenga duka lako.</p><p>Unakubali kuweka maudhui ya biashara halisi tu — bidhaa unazouza, duka lako, na kazi yako. Maudhui binafsi yasiyo ya biashara hayaruhusiwi.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">5. Maoni</h2><p>Wanunuzi wanaweza kutoa maoni tu baada ya kukamilisha oda na muuzaji. Maoni lazima yaakisi uzoefu halisi. Wauzaji wanaweza kujibu mara moja kwa kila maoni. Tunahifadhi haki ya kuondoa maoni yanayokiuka Masharti haya.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">6. Tabia zisizoruhusiwa</h2><p>Huruhusiwi: kuorodhesha bidhaa haramu; kujifanya mtu au biashara nyingine; kunyanyasa au kutishia watumiaji wengine; kuwasilisha maoni, ripoti, au hati za uthibitisho za uongo; au kujaribu kupita mifumo yetu ya usimamizi.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">7. Usimamizi wa maudhui</h2><p>Tunaweza kuficha, kuonya, kusimamisha, au kupiga marufuku akaunti zinazokiuka Masharti haya, tukieleza sababu kwa mtumiaji husika. Maudhui yaliyoripotiwa na kuthibitishwa mara tatu au zaidi hufichwa moja kwa moja yakisubiri ukaguzi.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">8. Mahali na mawasiliano</h2><p>Baadhi ya vipengele (utafutaji wa karibu, uwasilishaji) hutumia mahali pa kifaa chako, ambao unaweza kukataa — Sokoni itarudi kwenye uchaguzi wa mkoa/wilaya kwa mkono. Ujumbe wa ndani ya programu kati ya wanunuzi na wauzaji unaweza kusomwa na timu yetu ya usimamizi ikiwa umeripotiwa.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">9. Kusitisha</h2><p>Unaweza kuacha kutumia Sokoni wakati wowote. Tunaweza kusimamisha au kufuta akaunti zinazokiuka Masharti haya.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">10. Mabadiliko ya Masharti haya</h2><p>Tunaweza kusasisha Masharti haya mara kwa mara. Mabadiliko makubwa yatahitaji ukubali toleo jipya kabla ya kuendelea kutumia Sokoni.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">11. Sheria inayotawala</h2><p>Masharti haya yanatawaliwa na sheria za Jamhuri ya Muungano wa Tanzania.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">12. Mawasiliano</h2><p>Maswali kuhusu Masharti haya yanaweza kutumwa kwa support@sokoni.co.tz.</p></section>
    </div>
@else
    <h1 class="text-2xl font-bold">Terms of Service — version {{ \App\Support\Legal::TERMS_VERSION }}</h1>
    <p class="mt-4 text-sm text-sokoni-black/50">Last updated: 2026</p>
    <div class="prose prose-sm mt-24 max-w-none space-y-16 text-sokoni-black/80">
        <section><h2 class="font-semibold text-sokoni-black">1. Who we are</h2><p>Sokoni ("we", "us") operates the Sokoni marketplace app and website, connecting buyers and sellers in Tanzania. These Terms govern your use of Sokoni.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">2. Your account</h2><p>You may browse Sokoni without an account. Creating an account (via phone number, Google, or Apple) is required to place an order, message a seller, or save favourites. You're responsible for keeping your account credentials secure and for all activity under your account.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">3. Buying on Sokoni</h2><p>Sokoni is a marketplace connecting buyers and sellers — we are not a party to the sale itself. Orders, pricing, delivery and payment terms are agreed between you and the seller. Payment on the platform today is cash on delivery or pay on pickup only.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">4. Selling on Sokoni</h2><p>To sell, you must complete seller registration, including providing a valid NIDA (National Identification Authority) number and a photo of your ID, plus a business or trading licence. This information is used solely for manual identity and business verification by our team and is never shown publicly. Submitting false or fraudulent identity or licence information will result in account suspension or termination.</p><p>Your shop and products may be visible to buyers once your account is verified. Until verification, your products remain hidden from public search and browsing, though you may continue building your shop.</p><p>You agree to list only genuine business content — products you're actually selling, your shop, and your work. Personal, non-business content is not permitted.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">5. Reviews</h2><p>Buyers may leave a review only after completing an order with a seller. Reviews must reflect a genuine experience. Sellers may reply once to each review. We reserve the right to remove reviews that violate these Terms.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">6. Prohibited conduct</h2><p>You may not: list prohibited or illegal goods; impersonate another person or business; harass, threaten, or abuse other users; submit fraudulent reviews, reports, or verification documents; or attempt to circumvent our moderation or verification systems.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">7. Content moderation</h2><p>We may hide, warn, suspend, or ban accounts that violate these Terms, with reasons communicated to the affected user. Content reported and upheld three or more times is automatically hidden pending review.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">8. Location and communication</h2><p>Some features (nearby search, delivery) use your device location, which you can decline — Sokoni falls back to manual region/district selection. In-app messages between buyers and sellers may be read by our moderation team if reported.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">9. Termination</h2><p>You may stop using Sokoni at any time. We may suspend or terminate accounts that violate these Terms.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">10. Changes to these Terms</h2><p>We may update these Terms from time to time. Material changes will require you to accept the new version before continuing to use Sokoni.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">11. Governing law</h2><p>These Terms are governed by the laws of the United Republic of Tanzania.</p></section>
        <section><h2 class="font-semibold text-sokoni-black">12. Contact</h2><p>Questions about these Terms can be sent to support@sokoni.co.tz.</p></section>
    </div>
@endif
</article>
@endsection
